name: basic-ml
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - pandas=2.1.1
  - numpy=1.24.3
  - scipy=1.10.1
  - scikit-learn=1.3.0
  - matplotlib=3.7.1
  - tqdm=4.65.0
  - docopt=0.6.2
  - notebook=6.5.4
  - pip=23.2.1
  - tensorboard
  - pip:
    - sentencepiece
    - sacrebleu
    - nltk
    - timeout_decorator
    - "--find-links https://download.pytorch.org/whl/torch_stable.html"
    - torch==2.0.1; sys_platform != "linux" and sys_platform != "win32"
    - torch==2.0.1+cpu; sys_platform == "linux" or sys_platform == "win32"